# -*- coding: utf-8 -*-
"""Condiçoes em python (aula 5)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2HyNh8mRJUX0W_838Z2ZjtoRn_anrXt
"""

tempo = int(input('Quantos anos tem seu carro?'))
if tempo <=3:
  print('carro novo')
else:
  print('carro velho')
print('--fim--')

tempo = int(input('Quantos anos tem seu carro?'))
print('carro novo' if tempo<=3 else'carro velho')
print('--fim--')



n1 = float(input('Digite a primeira nota:'))
n2 = float(input('Digite a segunda nota:'))
media = (n1+n2)/2
print('A sua média foi: {:.1f}'.format(media))
if media >= 6.0:
  print('Parabéns você foi aprovado!')
else:
  print('Você esta de recuperação!')
