# -*- coding: utf-8 -*-
"""condiçoes aninhadas em python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agw7nGUafxCfCsvFuHDvcLmaYUrp9k-W
"""

