# -*- coding: utf-8 -*-
"""Condiçoes em python (aula 5)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2HyNh8mRJUX0W_838Z2ZjtoRn_anrXt
"""

tempo = int(input('Quantos anos tem seu carro?'))
if tempo <=3:
  print('carro novo')
else:
  print('carro velho')
print('--fim--')

tempo = int(input('Quantos anos tem seu carro?'))
print('carro novo' if tempo<=3 else'carro velho')
print('--fim--')