# -*- coding: utf-8 -*-
"""Condiçoes em python (aula 5)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2HyNh8mRJUX0W_838Z2ZjtoRn_anrXt
"""

tempo = int(input('Quantos anos tem seu carro?'))
if tempo <=3:
  print('carro novo')
else:
  print('carro velho')
print('--fim--')

tempo = int(input('Quantos anos tem seu carro?'))
print('carro novo' if tempo<=3 else'carro velho')
print('--fim--')



n1 = float(input('Digite a primeira nota:'))
n2 = float(input('Digite a segunda nota:'))
media = (n1+n2)/2
print('A sua média foi: {:.1f}'.format(media))
if media >= 6.0:
  print('Parabéns você foi aprovado!')
else:
  print('Você esta de recuperação!')

''''
**Desafio 29**

Escreva um programa que leia a velocidade de um carro. Se ele ultrapassar 80Km/h, mostre uma mensagem dizendo que ele foi multado. A multa vai custar R$7,00 por cada Km acima do limite.''''
velocidade= int(input("Digite a velocidade do carro:"))
multa= (velocidade-80)*7
if velocidade <=80:
  print('Dentro do padrãp de velocidade!')
else:
  print('Você foi multado no valor de R${}'.format(multa))
