# -*- coding: utf-8 -*-
"""condiçoes aninhadas em python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agw7nGUafxCfCsvFuHDvcLmaYUrp9k-W
"""
''''**Desafio 036**

Escreva um programa para aprovar o empréstimo bancário para a compra de uma casa. Pergunte o valor da casa, o salário do comprador e em quantos anos ele vai pagar. A prestação mensal não pode exceder 30% do salário ou então o empréstimo será negado.
''''
valor_casa= float(input('Digite o valor da casa:'))
salario_comprador= float(input('Digite o salário:'))
qntd_anos_pagamento= int(input('Digite em quantos anos pretende pagar:'))
calculo_prestacao= valor_casa/(qntd_anos_pagamento*12)
calculo= salario_comprador*0.3
print(f'\nPara pagar uma casa de R${valor_casa:.2f} em {qntd_anos_pagamento} anos, a prestação será de R${calculo_prestacao:.2f}.')
if calculo_prestacao>calculo:
  print('Prestação mensal muito alta, empréstimo negado!')
elif calculo_prestacao <=calculo:
  print('Empréstimo aprovado!!!')

''''**Desafio 038**

 Escreva um programa que leia dois números inteiros e compare-os. mostrando na tela uma mensagem:

– O primeiro valor é maior

– O segundo valor é maior

– Não existe valor maior, os dois são iguais''''
num_1= int(input('Digite um número inteiro:'))
num_2= int(input('Digite outro número inteiro:'))
if num_1 > num_2:
  print('O primeiro valor ({}) é maior'.format(num_1))
elif num_2 > num_1:
  print('O segundo valor ({}) é maior'.format(num_2))
else :
  print('Não existe valor maior, os dois são iguais')

