# -*- coding: utf-8 -*-
"""Módulos do Python (aula 4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_xgMqUgd2LvL_10HDXtr2SzgfXEWnbY

Em python para incluir algo é utilizado o comando "import"

comando "from" é para importar um módulo específico

**Bibliotecas mais utilizadas:**

math:
ceil
florr,
trunc,
pow,
sqrt,
factorial,

Calculo raiz quadrada
"""

import math
num = int(input('Digite um número:'))
raiz= math.sqrt(num)
print('A raiz de {} é igual a {}'.format(num,raiz))
