# -*- coding: utf-8 -*-
"""Módulos do Python (aula 4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_xgMqUgd2LvL_10HDXtr2SzgfXEWnbY

Em python para incluir algo é utilizado o comando "import"

comando "from" é para importar um módulo específico

**Bibliotecas mais utilizadas:**

math:
ceil(x)-Teto de x , o menor inteiro maior ou igual a x
florr(x)-Piso de x , o maior inteiro menor ou igual a x
trunc(x)
pow(x)
sqrt(x)-Raiz quadrada de x
factorial(x)

Calculo raiz quadrada
"""

import math
num = int(input('Digite um número:'))
raiz= math.sqrt(num)
print('A raiz de {} é igual a {}'.format(num,raiz))

from math import sqrt
num = int(input('Digite um número:'))
raiz= sqrt(num)
print('A raiz de {} é igual a {}'.format(num,raiz))

"""**Desafio 016**
Crie um programa que leia um número Real qualquer e mostre na tela a sua porção inteira"""

from math import trunc
num = float(input('Digite um número real:'))
pt= trunc(num)
print(pt)



