# -*- coding: utf-8 -*-
"""Módulos do Python (aula 4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_xgMqUgd2LvL_10HDXtr2SzgfXEWnbY
"""

