# -*- coding: utf-8 -*-
"""Operações com string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGxTbVQbzvoXEf_DYapR6Jd6_gD9wjyL
"""

''''**Desafio 022**

Crie um programa que leia o nome completo de uma pessoa e mostre:

– O nome com todas as letras maiúsculas e minúsculas.

– Quantas letras ao todo (sem considerar espaços).

– Quantas letras tem o primeiro nome.''''

nome = str(input("Digite o seu nome completo: ")).strip()


print("Analisando seu nome...")
print(f"Seu nome em maiúsculas é {nome.upper()}")
print(f"Seu nome em minúsculas é {nome.lower()}")

total_letras = len(nome) - nome.count(" ")
print(f"Seu nome tem ao todo {total_letras} letras")

primeiro_nome = nome.split()[0]
print(f"Seu primeiro nome é {primeiro_nome} e ele tem {len(primeiro_nome)} letras")
