# -*- coding: utf-8 -*-
"""Operadores Aritiméticos (aula 3) 29/09/2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SdRMGQUid-zRL_1ehUo970jiV2zZrSs4

(+) Adição

(-) Subtração

(*) Multiplicação

(/) Divisão

(**) Potência

(//) Divisão inteira

(%) Resto da divisão

# **Ordem de precedência**

1 () no python utiliza-se somente parênteses

2 **

3 * / // % -> fazer quem aparece primeiro

4 + -
"""

n1 = int(input('Digite um valor:'))
n2 = int(input('Outro valor:'))
s = n1 + n2
m = n1 * n2
d = n1 / n2
di = n1 // n2
e = n1 ** n2
print('A soma é {}, \n o produto é {}'.format(s , m, d))
print('A divisão inteira é {} \n e a potência é {}'.format(di, e) )

"""**Desafio 005**

Faça um programa que leia um número inteiro e mostre na tela o seu sucessor e seu antecessor
"""

num = int(input("Digite um número:"))
ant = num -1
suc = num+1
print("Número escolhido:{}\n Número Antecessor:{}\n Número Sucessor:{}".format(num, ant, suc))

"""**Desafio 006**

Crie um algoritmo que leia um número e mostre o seu dobro, triplo e raiz quadrada

"""

num = int(input("DIgite um número:"))
dobro = num *2
triplo = num *3
raizq= num **0.5
print ("dobro é :{}\n triplo é :{}\n a raiz quadrada é:{}".format(dobro, triplo, raizq))

"""**Desafio 007**

Desenvolva um programa que leia as duas notas de um aluno, calcule e mostre a sua média

"""

nota1 = float(input('Digite a primeira nota:'))
nota2 = float(input('Digite a segunda nota:'))
media = (nota1+nota2) /2
print('A média da nota é:', media)

"""**Desafio 008**

Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros
metro= int(input('Digite um valor em metros:'))
cm= metro*100
mm= metro*1000
print('{}cm,{}mm'.format(cm, mm))

"""

metro= float(input('Digite um valor em metros:'))
cm= metro*100
mm= metro*1000
print('{}cm,{}mm'.format(cm, mm))

"""**Desafio 009**

Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada
"""



"""**Desafio 010**

Crie um programa que leia quanto uma pessoa tem na carteira e mostre quantos dólares ela pode comprar.

Considere US$1.00=R$3.27
"""
din= int(input('Quantos reais possui na carteira?'))
conv= din/3.27
print('Você poderá comprar {} doláres!'.format(conv))


"""**Desafio 011**

Faça um programa que leia a largura e a altura de uma parede em metros, calcule a sua área e a quantidade de tinta necessária para pinta-la, sabendo que cada litro de tinta pinta uma área de 2m²
"""
print('Digite valores em metros!!!')
altu= int(input('Qual é a altura da parede?'))
larg= int(input('Qual é a largura da parede?'))
cal= altu*larg
tinta= cal/2
print('A área da parece é de {} m² e a quantidade de tinta necessaária para pintar é de {} litros'.format(cal, tinta))


"""**Desafio 012**

Faça um algoritmo que leia o preço de um produto e mostre seu novo preço, com 5% de desconto
"""
prod= int(input('Digite o preço do produto:'))
desc= prod*0.95
print('O preço final do produto com o desconto de 5% é de: {}'.format(desc))



"""**Desafio 013**

Faça um algoritmo que leia o salário de um funcionário  e mostre seu novo salário com 15% de aumento.
"""
slr= int(input('Digite o salário do funcionário:'))
cal= slr*1.15
print('O novo salário é de R${}'.format(cal))


"""**Desafio 014**

Escreva um programa que converta uma temperatura digitada em Cº para F
"""



"""**Desafio 015**

Escreva um programa que pergunte a quantidade de Km percorridos por um carro alugado e a quantidade de dias pelos quais ele foi alugado. Calcule o preço a pagar, sabendo que o custa R$ 60.00  por dia  e  R$ 0.15 por km rodado
"""
km= int(input('Quantos km foram percorridos pelo carro?'))
dias= int(input('Por quantos dias o carro foi alugado?'))
calkm= 0.15*km
caldias= 60.00*dias
pf= calkm+caldias
print('O preço a ser pago é de R$ {} '.format(pf))
