# -*- coding: utf-8 -*-
"""Primeiros comandos Python (aula 1) 28/09/2026 

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kaGkF6AzXmD8fV3Zq_wmDv6S26pPrexG
"""

print('Olá mundo')

"""Para python números não ficam entre aspas, aspas somente quando quer escrever algo na tela"""

print(7+4) #imprime resultado

"""Em python toda variável é um objeto, e pode receber valores "="

"""

nome = "Maria"
idade = 20
print(nome,idade)

"""Para perguntar para o usuario inserir input (interação)

"""

nome = input("Qual é o seu nome?")

nome = input("Qual é o seu nome?")
idade = input("Qual é a sua idade?")

"""Desafio 1 -
Crie um script que leia o nome de uma pessoa e mostre uma mensagem de boas vindas de acordo com o valor digitado
"""

Nome = input("Qual é o seu nome?")
print("Boas vindas,",nome,"!")

"""Desafio 2 - Crie um script que leia o dia, o mês e o ano de nascimento de uma pessoa e mostre uma mensagem com a data formatada

"""

dia = input("Digite o dia do seu nascimento:")
mes = input("Digite o mês do seu nascimento:")
ano = input("Digite o ano do seu nascimento:")
print('Você nasceu em:',dia,'/',mes,'/',ano)

"""Desafio 3 - Crie um script python que leia dois números e tente mostrar a soma"""

num1 = input("digite o primeiro número:")
num2 = input("digite o segundo número:")
soma = num1 + num2
print("a soma dos números é:", num1+num2)
