# -*- coding: utf-8 -*-
"""Tipos primitivos de dados (aula 2) 28/09/2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9C_WFn7Y3mS_e6MML1MFhb6OycyEI1t

Python tem 4 tipos primitivos principais

int=números inteiros (7,-4,0)

float=números reais (4.5,0.078,-15.223) ponto flutuante

bool=valores lógicos ou booleanos (True,False) verdadeiro ou falso

str= valores de caracteres ('ola')

Refazendo exercicio 3 de forma correta agora
(adicionando tipo primitivo)
"""

num1 = input("digite o primeiro número:")
num2 = input("digite o segundo número:")
soma = num1 + num2
print("a soma dos números é:", soma)

num1 = int( input("digite o primeiro número:"))
num2 = int (input("digite o segundo número:"))
soma = num1 + num2
print("a soma dos números é:", soma)

num1 = int( input("digite o primeiro número:"))
num2 = int (input("digite o segundo número:"))
soma = num1 + num2
print("a soma entre {} e {} vale {}".format(num1,num2,soma))
